export const redirects = JSON.parse("{\"/%E4%BC%98%E7%A7%80%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/C++%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%E5%88%86%E4%BA%AB.html\":\"/%E4%BC%98%E7%A7%80%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/C__%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%E5%88%86%E4%BA%AB.html\"}")

export const routes = Object.fromEntries([
  ["/about.html", { loader: () => import(/* webpackChunkName: "about.html" */"D:/my-docs/src/.vuepress/.temp/pages/about.html.js"), meta: {"title":"关于我","index":false} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/my-docs/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"主页","icon":"house"} }],
  ["/datastruct/%E5%88%86%E5%B8%83%E5%BC%8F%E5%85%B1%E8%AF%86%E7%AE%97%E6%B3%95.html", { loader: () => import(/* webpackChunkName: "datastruct_分布式共识算法.html" */"D:/my-docs/src/.vuepress/.temp/pages/datastruct/分布式共识算法.html.js"), meta: {"category":["分布式"],"tag":["分布式"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.99,"words":1798},"title":"分布式共识算法基础","type":"article"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"category":["使用指南"],"tag":["禁用"],"excerpt":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","readingTime":{"minutes":0.43,"words":128},"title":"布局与功能禁用","icon":"gears","order":4,"type":"article"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"category":["使用指南"],"tag":["加密"],"isEncrypted":true,"readingTime":{"minutes":0.51,"words":154},"title":"密码加密的文章","icon":"lock","type":"article"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"category":["指南"],"tag":["布局"],"excerpt":"<p>布局包括:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">导航栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">侧边栏</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/zh/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">页脚</a></li>\n</ul>","readingTime":{"minutes":0.53,"words":159},"title":"布局","icon":"object-group","order":2,"type":"article"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"category":["使用指南"],"tag":["Markdown"],"excerpt":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你需要创建并编写 Markdown，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","readingTime":{"minutes":3.47,"words":1041},"title":"Markdown 展示","icon":"fa6-brands:markdown","order":2,"type":"article"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"author":"Ms.Hope","date":1577836800000,"category":["使用指南"],"tag":["页面配置","使用指南"],"sticky":true,"cover":"/assets/images/cover1.jpg","excerpt":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","readingTime":{"minutes":1.76,"words":529},"title":"页面配置","icon":"file","order":3,"type":"article"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"category":["使用指南"],"readingTime":{"minutes":0.07,"words":22},"title":"主要功能与配置演示","icon":"laptop-code","type":"article"} }],
  ["/posts/cherry.html", { loader: () => import(/* webpackChunkName: "posts_cherry.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/cherry.html.js"), meta: {"date":1641686400000,"category":["樱桃"],"tag":["红","小","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":33},"title":"樱桃","icon":"pen-to-square","type":"article"} }],
  ["/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "posts_dragonfruit.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/dragonfruit.html.js"), meta: {"date":1641772800000,"category":["火龙果","水果"],"tag":["红","大"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"火龙果","icon":"pen-to-square","type":"article"} }],
  ["/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "posts_strawberry.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/strawberry.html.js"), meta: {"date":1641859200000,"category":["水果","草莓"],"tag":["红","小"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"草莓","icon":"pen-to-square","type":"article"} }],
  ["/posts/tomato.html", { loader: () => import(/* webpackChunkName: "posts_tomato.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/tomato.html.js"), meta: {"date":1641945600000,"category":["蔬菜"],"tag":["红","圆"],"sticky":true,"cover":"/assets/images/cover2.jpg","excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.13,"words":38},"title":"番茄","icon":"pen-to-square","type":"article"} }],
  ["/posts/%E4%BD%BF%E7%94%A8VuePress%E6%9E%84%E5%BB%BA%E4%B8%AA%E4%BA%BA%E7%9F%A5%E8%AF%86%E7%BD%91%E7%AB%99.html", { loader: () => import(/* webpackChunkName: "posts_使用VuePress构建个人知识网站.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/使用VuePress构建个人知识网站.html.js"), meta: {"date":1745115358000,"category":["建站","VuePress"],"tag":["建站","VuePress"],"excerpt":"<p>VuePress 是一个基于 Vue.js 的静态网站生成器，最初由 Vue.js 核心团队成员 Evan You (尤雨溪) 创建，主要用于编写技术文档，但现已发展为一个功能强大的静态站点生成工具。适合构建个人网站、博客或文档站点。下面详细记录构建过程！</p>\n<h2>创建项目</h2>\n<p><strong>第一步：安装 Node.js。</strong></p>\n<p>MacOS 使用 HomeBrew 安装。</p>\n<div class=\"language-shell line-numbers-mode\" data-highlighter=\"shiki\" data-ext=\"shell\" style=\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\"><pre class=\"shiki shiki-themes one-light one-dark-pro vp-code\"><code><span class=\"line\"><span style=\"--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic\"># 安装node</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\">brew</span><span style=\"--shiki-light:#50A14F;--shiki-dark:#98C379\"> install</span><span style=\"--shiki-light:#50A14F;--shiki-dark:#98C379\"> node</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\">node</span><span style=\"--shiki-light:#986801;--shiki-dark:#D19A66\"> -v</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\">npm</span><span style=\"--shiki-light:#986801;--shiki-dark:#D19A66\"> -v</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic\"># 升级npm</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\">npm</span><span style=\"--shiki-light:#50A14F;--shiki-dark:#98C379\"> install</span><span style=\"--shiki-light:#986801;--shiki-dark:#D19A66\"> -g</span><span style=\"--shiki-light:#50A14F;--shiki-dark:#98C379\"> npm@11.3.0</span></span></code></pre>\n<div class=\"line-numbers\" aria-hidden=\"true\" style=\"counter-reset:line-number 0\"><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div></div></div>","readingTime":{"minutes":8.95,"words":2685},"title":"使用VuePress构建个人知识网站","type":"article"} }],
  ["/%E4%BC%98%E7%A7%80%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/C__%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE%E5%88%86%E4%BA%AB.html", { loader: () => import(/* webpackChunkName: "优秀开源代码_C__开源项目分享.html" */"D:/my-docs/src/.vuepress/.temp/pages/优秀开源代码/C__开源项目分享.html.js"), meta: {"date":1745541381000,"category":["开源代码"],"tag":["开源代码"],"excerpt":"<h2><a class=\"header-anchor\" href=\"#高性能日志库-spdlog\"><span>高性能日志库：</span></a><a href=\"https://github.com/gabime/spdlog/\" target=\"_blank\" rel=\"noopener noreferrer\">SpdLog</a></h2>\n<h2><a class=\"header-anchor\" href=\"#高性能通用-mpmc-无锁队列-concurrentqueue\"><span>高性能通用 MPMC 无锁队列：</span></a><a href=\"https://github.com/cameron314/concurrentqueue\" target=\"_blank\" rel=\"noopener noreferrer\">ConcurrentQueue</a></h2>","readingTime":{"minutes":0.49,"words":146},"title":"C++开源项目分享","type":"article"} }],
  ["/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "posts_apple_1.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/apple/1.html.js"), meta: {"date":1640995200000,"category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.11,"words":34},"title":"苹果 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "posts_apple_2.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/apple/2.html.js"), meta: {"date":1641081600000,"category":["苹果"],"tag":["红","大","圆"],"excerpt":"\n<p>一个被星标了的苹果文章。</p>\n","readingTime":{"minutes":0.16,"words":48},"title":"苹果 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "posts_apple_3.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/apple/3.html.js"), meta: {"date":1641168000000,"category":["苹果","水果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"苹果 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "posts_apple_4.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/apple/4.html.js"), meta: {"date":1641254400000,"category":["苹果","水果"],"tag":["红","大","圆"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"苹果 4","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "posts_banana_1.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/banana/1.html.js"), meta: {"date":1641340800000,"category":["香蕉","水果"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.13,"words":38},"title":"香蕉 1","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "posts_banana_2.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/banana/2.html.js"), meta: {"date":1641427200000,"category":["香蕉","水果"],"tag":["黄","弯曲的","长"],"excerpt":"\n<p>一个被数字 <code>10</code> 星标了的香蕉文章。</p>\n","readingTime":{"minutes":0.18,"words":55},"title":"香蕉 2","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "posts_banana_3.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/banana/3.html.js"), meta: {"date":1641513600000,"category":["香蕉"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"香蕉 3","icon":"pen-to-square","type":"article"} }],
  ["/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "posts_banana_4.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/banana/4.html.js"), meta: {"date":1641600000000,"category":["香蕉"],"tag":["黄","弯曲的","长"],"excerpt":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","readingTime":{"minutes":0.12,"words":36},"title":"香蕉 4","icon":"pen-to-square","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%20copy%202.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_http从入门到精通 copy 2.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/http从入门到精通 copy 2.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.98,"words":1795},"title":"HTTP从入门到精通3","icon":"folder","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%20copy.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_http从入门到精通 copy.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/http从入门到精通 copy.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.98,"words":1793},"title":"HTTP从入门到精通2","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_http从入门到精通.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/http从入门到精通.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>动态字符串类型</h2>\n<h3>动态字符串类型</h3>\n<h4>动态字符串类型</h4>\n<h5>动态字符串类型</h5>\n<h6>动态字符串类型</h6>\n<p>####### 动态字符串类型</p>\n<p>redis 使用了一种 SDS（simple dynamic string）类型的动态字符串，作为默认字符串的表示，并没有直接使用 C 语言中的字符串。</p>\n<p>并且字符串的的<strong>键和值</strong>对在底层都是由 SDS 实现，因为键值对的键是一个字符串对象，字符串的值也是一个对象。</p>\n<p>如果 list 中存储的也是字符串，那么列表中的每个字符串也都是 SDS 结构。</p>","readingTime":{"minutes":5.19,"words":1557},"title":"HTTP从入门到精通","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C1%20copy%202.html", { loader: () => import(/* webpackChunkName: "教程_计算机网络_计算机网络1 copy 2.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/计算机网络/计算机网络1 copy 2.html.js"), meta: {"category":["计算机网络"],"tag":["计算机网络"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":6,"words":1799},"title":"计算机网络1","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C1%20copy.html", { loader: () => import(/* webpackChunkName: "教程_计算机网络_计算机网络1 copy.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/计算机网络/计算机网络1 copy.html.js"), meta: {"category":["计算机网络"],"tag":["计算机网络"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":6,"words":1799},"title":"计算机网络3","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C1.html", { loader: () => import(/* webpackChunkName: "教程_计算机网络_计算机网络1.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/计算机网络/计算机网络1.html.js"), meta: {"category":["计算机网络"],"tag":["计算机网络"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":6,"words":1799},"title":"计算机网络2","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/HTTP2/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%20copy%202.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_HTTP2_http从入门到精通 copy 2.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/HTTP2/http从入门到精通 copy 2.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.98,"words":1795},"title":"HTTP从入门到精通3","icon":"folder","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/HTTP2/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%20copy.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_HTTP2_http从入门到精通 copy.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/HTTP2/http从入门到精通 copy.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.98,"words":1793},"title":"HTTP从入门到精通2","type":"article"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/HTTP2/http%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A.html", { loader: () => import(/* webpackChunkName: "教程_HTTP_HTTP2_http从入门到精通.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/HTTP2/http从入门到精通.html.js"), meta: {"category":["HTTP"],"tag":["HTTP"],"excerpt":"<h2>为什么需要分布式共识算法？</h2>\n<p>思考：现在你有一份随时变动的数据，需要确保它正确存储在网络的几台不同机器上，并且要保证数据是随时可用的，应该怎么做？</p>\n<p>在分布式环境下，可以不必去追求系统内所有节点在任何情况下的数据状态都一致，采用“少数服从多数”的原则，认为数据的变化被正确存储在系统中。因此，我们需要一种算法，能够让分布式系统内部暂时容忍节点存在不同的状态，但最终大多数节点的状态能够一致。这种让系统能最终表现出整体一致性的过程，就是各个节点的<strong>协商共识</strong>。</p>\n<p>分布式共识算法广泛用在：分布式数据库确保数据的一致性，分布式系统集群管理，状态机复制等。</p>","readingTime":{"minutes":5.97,"words":1792},"title":"HTTP从入门到精通","type":"article"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/my-docs/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/datastruct/", { loader: () => import(/* webpackChunkName: "datastruct_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/datastruct/index.html.js"), meta: {"title":"Datastruct"} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"title":"Posts"} }],
  ["/%E4%BC%98%E7%A7%80%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/", { loader: () => import(/* webpackChunkName: "优秀开源代码_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/优秀开源代码/index.html.js"), meta: {"title":"优秀开源代码"} }],
  ["/posts/apple/", { loader: () => import(/* webpackChunkName: "posts_apple_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/apple/index.html.js"), meta: {"title":"Apple"} }],
  ["/posts/banana/", { loader: () => import(/* webpackChunkName: "posts_banana_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/posts/banana/index.html.js"), meta: {"title":"Banana"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/", { loader: () => import(/* webpackChunkName: "教程_HTTP_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/index.html.js"), meta: {"title":"HTTP"} }],
  ["/%E6%95%99%E7%A8%8B/", { loader: () => import(/* webpackChunkName: "教程_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/index.html.js"), meta: {"title":"教程"} }],
  ["/%E6%95%99%E7%A8%8B/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/", { loader: () => import(/* webpackChunkName: "教程_计算机网络_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/计算机网络/index.html.js"), meta: {"title":"计算机网络"} }],
  ["/%E6%95%99%E7%A8%8B/HTTP/HTTP2/", { loader: () => import(/* webpackChunkName: "教程_HTTP_HTTP2_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/教程/HTTP/HTTP2/index.html.js"), meta: {"title":"HTTP2"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"分类","index":false} }],
  ["/category/%E5%88%86%E5%B8%83%E5%BC%8F/", { loader: () => import(/* webpackChunkName: "category_分布式_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/分布式/index.html.js"), meta: {"title":"分布式 分类","index":false} }],
  ["/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_使用指南_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/使用指南/index.html.js"), meta: {"title":"使用指南 分类","index":false} }],
  ["/category/%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "category_指南_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/指南/index.html.js"), meta: {"title":"指南 分类","index":false} }],
  ["/category/%E6%A8%B1%E6%A1%83/", { loader: () => import(/* webpackChunkName: "category_樱桃_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/樱桃/index.html.js"), meta: {"title":"樱桃 分类","index":false} }],
  ["/category/%E7%81%AB%E9%BE%99%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_火龙果_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/火龙果/index.html.js"), meta: {"title":"火龙果 分类","index":false} }],
  ["/category/%E6%B0%B4%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_水果_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/水果/index.html.js"), meta: {"title":"水果 分类","index":false} }],
  ["/category/%E8%8D%89%E8%8E%93/", { loader: () => import(/* webpackChunkName: "category_草莓_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/草莓/index.html.js"), meta: {"title":"草莓 分类","index":false} }],
  ["/category/%E8%94%AC%E8%8F%9C/", { loader: () => import(/* webpackChunkName: "category_蔬菜_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/蔬菜/index.html.js"), meta: {"title":"蔬菜 分类","index":false} }],
  ["/category/%E5%BB%BA%E7%AB%99/", { loader: () => import(/* webpackChunkName: "category_建站_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/建站/index.html.js"), meta: {"title":"建站 分类","index":false} }],
  ["/category/vuepress/", { loader: () => import(/* webpackChunkName: "category_vuepress_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/vuepress/index.html.js"), meta: {"title":"VuePress 分类","index":false} }],
  ["/category/%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/", { loader: () => import(/* webpackChunkName: "category_开源代码_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/开源代码/index.html.js"), meta: {"title":"开源代码 分类","index":false} }],
  ["/category/%E8%8B%B9%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "category_苹果_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/苹果/index.html.js"), meta: {"title":"苹果 分类","index":false} }],
  ["/category/%E9%A6%99%E8%95%89/", { loader: () => import(/* webpackChunkName: "category_香蕉_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/香蕉/index.html.js"), meta: {"title":"香蕉 分类","index":false} }],
  ["/category/http/", { loader: () => import(/* webpackChunkName: "category_http_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/http/index.html.js"), meta: {"title":"HTTP 分类","index":false} }],
  ["/category/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/", { loader: () => import(/* webpackChunkName: "category_计算机网络_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/category/计算机网络/index.html.js"), meta: {"title":"计算机网络 分类","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"标签","index":false} }],
  ["/tag/%E5%88%86%E5%B8%83%E5%BC%8F/", { loader: () => import(/* webpackChunkName: "tag_分布式_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/分布式/index.html.js"), meta: {"title":"标签: 分布式","index":false} }],
  ["/tag/%E7%A6%81%E7%94%A8/", { loader: () => import(/* webpackChunkName: "tag_禁用_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/禁用/index.html.js"), meta: {"title":"标签: 禁用","index":false} }],
  ["/tag/%E5%8A%A0%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_加密_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/加密/index.html.js"), meta: {"title":"标签: 加密","index":false} }],
  ["/tag/%E5%B8%83%E5%B1%80/", { loader: () => import(/* webpackChunkName: "tag_布局_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/布局/index.html.js"), meta: {"title":"标签: 布局","index":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"title":"标签: Markdown","index":false} }],
  ["/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/", { loader: () => import(/* webpackChunkName: "tag_页面配置_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/页面配置/index.html.js"), meta: {"title":"标签: 页面配置","index":false} }],
  ["/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/", { loader: () => import(/* webpackChunkName: "tag_使用指南_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/使用指南/index.html.js"), meta: {"title":"标签: 使用指南","index":false} }],
  ["/tag/%E7%BA%A2/", { loader: () => import(/* webpackChunkName: "tag_红_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/红/index.html.js"), meta: {"title":"标签: 红","index":false} }],
  ["/tag/%E5%B0%8F/", { loader: () => import(/* webpackChunkName: "tag_小_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/小/index.html.js"), meta: {"title":"标签: 小","index":false} }],
  ["/tag/%E5%9C%86/", { loader: () => import(/* webpackChunkName: "tag_圆_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/圆/index.html.js"), meta: {"title":"标签: 圆","index":false} }],
  ["/tag/%E5%A4%A7/", { loader: () => import(/* webpackChunkName: "tag_大_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/大/index.html.js"), meta: {"title":"标签: 大","index":false} }],
  ["/tag/%E5%BB%BA%E7%AB%99/", { loader: () => import(/* webpackChunkName: "tag_建站_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/建站/index.html.js"), meta: {"title":"标签: 建站","index":false} }],
  ["/tag/vuepress/", { loader: () => import(/* webpackChunkName: "tag_vuepress_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/vuepress/index.html.js"), meta: {"title":"标签: VuePress","index":false} }],
  ["/tag/%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81/", { loader: () => import(/* webpackChunkName: "tag_开源代码_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/开源代码/index.html.js"), meta: {"title":"标签: 开源代码","index":false} }],
  ["/tag/%E9%BB%84/", { loader: () => import(/* webpackChunkName: "tag_黄_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/黄/index.html.js"), meta: {"title":"标签: 黄","index":false} }],
  ["/tag/%E5%BC%AF%E6%9B%B2%E7%9A%84/", { loader: () => import(/* webpackChunkName: "tag_弯曲的_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/弯曲的/index.html.js"), meta: {"title":"标签: 弯曲的","index":false} }],
  ["/tag/%E9%95%BF/", { loader: () => import(/* webpackChunkName: "tag_长_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/长/index.html.js"), meta: {"title":"标签: 长","index":false} }],
  ["/tag/http/", { loader: () => import(/* webpackChunkName: "tag_http_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/http/index.html.js"), meta: {"title":"标签: HTTP","index":false} }],
  ["/tag/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/", { loader: () => import(/* webpackChunkName: "tag_计算机网络_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/tag/计算机网络/index.html.js"), meta: {"title":"标签: 计算机网络","index":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"文章","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"星标","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/my-docs/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"时间轴","index":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
